<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../HexagonalLab.Core/HexagonalLab.Core.csproj" />
    <ProjectReference Include="../../tests/HexagonalLab.Core.Tests/HexagonalLab.Core.Tests.csproj" />
    <ProjectReference Include="..\HexagonalLab.Infrastructure\HexagonalLab.Infrastructure.csproj" />
  </ItemGroup>

</Project>
